### ISSUE TITLE
Quick restart seems to inject but doesn't work. 

### ISSUE THREAD

**Issue by IlyaTaidi** [nicholassam6425/balatro-mods#1]
Highlighted in red in the mod settings gui too if that matters

**Comment by nicholassam6425** [comment]
do you have any other mods installed?

**Comment by nicholassam6425** [comment]
also, try deleting your balatro.exe then verifying game installation through steam.

**Comment by IlyaTaidi** [comment]
It was a balamod issue, feel free to close the ticket
