### ISSUE TITLE
[Request] Port to Steammodded

### ISSUE THREAD

**Issue by IlyaTaidi** [nicholassam6425/balatro-mods#2]
Now that steam modded has an injector, could this be ported to that mod loader?

**Comment by nicholassam6425** [comment]
do you want quick restart in particular in steammodded? if so, i might be able to port that over pretty quickly. but otherwise, i want to finish the center api first before anything

**Comment by IlyaTaidi** [comment]
Yes, literally just quick restart, this might be the most subtly goated mod out there right now

**Comment by nicholassam6425** [comment]
alright bet gimme a bit

**Comment by nicholassam6425** [comment]
added it, but i did it pretty roughly. just pop open another issue if problems arise and i'll figure it out
