### ISSUE TITLE
Coupon book and Hobby Shop

### ISSUE THREAD

**Issue by MarcinJaracz** [nicholassam6425/balatro-mods#4]
I don't know why, but these mods don't work for me. 
I've installed the Balamod with the centre API.
I can see the Balamod menu on the right-hand side. 
I can install other mods from this menu, but somehow these two mods just don't work.
I've tried installing different versions of Balamod, uninstalling all the mods from steamod loader.
Is there anything I'm missing here?
![image](https://github.com/nicholassam6425/balatro-mods/assets/48261401/10fd8303-61c0-40d7-86c8-18a838cfdc81)
![image](https://github.com/nicholassam6425/balatro-mods/assets/48261401/5055b1e7-12be-4465-b00b-74879dfeab53)
![image](https://github.com/nicholassam6425/balatro-mods/assets/48261401/64bb6bd7-948a-41fe-9392-72dce75bcc6b)

**Comment by MarcinJaracz** [comment]
An interesting thing just happened. In Balamod menu I disabled both mods and started a new game. In shop, I clicked re-roll and the game crashed. It might be connected...?
![image](https://github.com/nicholassam6425/balatro-mods/assets/48261401/0e1ea845-7dd1-439d-b901-1efd4610af24)

**Comment by MarcinJaracz** [comment]
Yep Coupon Book doesn't work either if I enable or disable it. 
The problem with the crash is related only to Hobby Shop mod.

**Comment by nicholassam6425** [comment]
these mods are intended for only balamod. you have steamodded installed. if the same issue persists without steamodded installed, lmk

**Comment by MarcinJaracz** [comment]
Thanks for replay.
Is there a way to rewrite it to make this mod work with both frameworks/mod loaders?

**Comment by nicholassam6425** [comment]
unfortunately, i'd have to basically write a whole new version on steamodded's version. i'm mostly dedicating my time on balamod. if i get a lot of requests to port this to steamodded, i'll consider it

**Comment by nicholassam6425** [comment]
also coupon book and hobby shop are incredibly incompatible with other mods, just by nature of the way they work

**Comment by MarcinJaracz** [comment]
I see. Thanks anyway.
