### ISSUE TITLE
Quick Restart crash when accepting Celestial Pack tag

### ISSUE THREAD

**Issue by JesseNoEyes** [nicholassam6425/balatro-mods#6]
Absolutely love this mod; this is the first issue I've encountered. 
I skipped a small blind for a Celestial Pack (Pick 2), and accidentally hit F2  after only selecting one planet. This caused the blinds to reroll and display overtop of the opened Pack. It crashed not long after. 
Thanks for all you do!

**Comment by nicholassam6425** [comment]
just pushed a change that i believe fixes this. if you encounter issues still, lmk. thanks for the report.
